# Generated by Django 4.0.6 on 2022-07-07 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortLink', models.TextField(max_length=100, validators=[django.core.validators.URLValidator()])),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=50)),
            ],
        ),
    ]
